version: "3.9"

services:
  db:
    image: mongo
    volumes:
      - ./db:/data/db

  api:
    build: ./api
    environment:
      - PORT=4000
      - MONGO_URI=${MONGO_URI}
      - JWT_SECRET=${JWT_SECRET}
    ports:
      - 4000:4000
    depends_on:
      - db

  app:
x    build:
      context: ./app
      dockerfile: Dockerfile
      args:
        - GITHUB_ID=${GITHUB_ID}
        - GITHUB_SECRET=${GITHUB_SECRET}
        - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
        - NEXTAUTH_URL=${NEXTAUTH_URL}
        - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
        - API_SCHEMA=${API_SCHEMA}
        - JWT_SECRET=${JWT_SECRET}

    ports:
      - 3000:3000
    depends_on:
      - api

volumes:
  db:
